services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    restart: unless-stopped
    init: true
    env_file: ./.env
    ports:
      - "8000:8000"
