services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    restart: unless-stopped
    init: true
    env_file: ./.env
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: satwikh_01
      POSTGRES_PASSWORD: "@Jc12"
      POSTGRES_DB: smart_feedback_system
    ports:
      - "5433:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
